version: '3'
services:
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
  mongodb:
    image: mongo:3.2.0
    ports:
    - "27017:27017"
    volumes:
    - dbvolume01:/data
    environment: {
      AUTH: "no"
    }
volumes:
  dbvolume01: {}
