version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    env_file: .env
  nats:
    image: nats:latest
    ports:
    - "4222:4222"
    - "8222:8222"
    - "6222:6222"
  kafka:
    image: spotify/kafka:latest
    environment:
      - ADVERTISED_HOST=127.0.0.1
      - ADVERTISED_PORT=9092
      - CONSUMER_THREADS=1
      - TOPICS=topic,some-other-topic,test
      - ZK_CONNECT=kafka7zookeeper:2181/root/path
      - GROUP_ID=mymirror
    ports:
      - "2181:2181"
      - "9092:9092"
  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
  mongodb:
    image: mongo:3.4.0
    ports:
    - "27017:27017"
    volumes:
    - dbvolume01:/data
    environment: {
      AUTH: "no"
    }
  mysql:
    image: mysql:5.7
    volumes:
    - ./p:/data
    ports:
    - "3306:3306"
    env_file: .env
  neo4j:
    image: tpires/neo4j
    volumes:
    - ./n:/data
    env_file: .env
    cap_add:
      - SYS_RESOURCE
    ports:
      - "7474:7474"
volumes:
  dbvolume01: {}
